### PR TITLE
Add retryOnConflict option

### PR DESCRIPTION
**Pull request by dinoshauer**
I haven't been able to reproduce the version conflict we got with this fix yet

### CODE REVIEW

**Comment by joshuakarjala** [comment]
shouldn't it be an individual option per function and not for the whole instance?

**Comment by dinoshauer** [comment]
Sure, that makes sense. One moment

**Comment by dinoshauer** [comment]
@joshuakarjala so either way it'll break backwards compatability.

Which implementation do you prefer? I'm leaning towards opts as that will break the least in the future:

```
// More args?
that.update = function (id, doc, retryOnConflict, cb) {
  if (retryOnConflict === undefined) retryOnConflict = 0;
  client.update({
    index: _INDEX,
    type: _TYPE,
    retryOnConflict: retryOnConflict,
    doc_as_upsert: true,
    id,
    body: {
      doc
    }
  }, cb);
};

// Or opts?
that.update = function (opts, cb) {
  client.update({
    index: _INDEX,
    type: _TYPE,
    retryOnConflict: opts.retryOnConflict || 0,
    doc_as_upsert: true,
    id: opts.id,
    body: {
      opts.doc
    }
  }, cb);
};
```

**Comment by joshuakarjala** [comment]
everything as opts

**Comment by dinoshauer** [comment]
I think we should do it on all methods and change all top level keys to `opts.*` (except for `type` and `index`) so as well on updates we'd need to supply `{ body: { doc: { ... } } }`, thoughts?

**Comment by joshuakarjala** [comment]
go for it

**Comment by dinoshauer** [comment]
@joshuakarjala can you have a look?

**Comment by joshuakarjala** [comment]
tak out type / links

**Comment by dinoshauer** [comment]
Yep. Done

**Comment by joshuakarjala** [comment]
published

**Pull request merged**
